// aes-256 gcm (Galois Counter Mode)

import crypto from "node:crypto";

const ALGORITHM = "aes-256-gcm";
const KEY_LENGTH = 32;
const IV_LENGTH = 12;


export const encryptAESGCM = (
    message, 
    sessionKey, 
    aad = null
    
) => {

    // Session key check
    if (!sessionKey) {
        throw new Error("Missing arguments is required");
    }

    if (sessionKey.length !== KEY_LENGTH) {
        throw new Error(
            "Mismatch of lengths requires a valid length"
        );
    }

    // GCM commonly uses a 12-byte IV/nonce
    const iv = crypto.randomBytes(IV_LENGTH);

    const cipher = crypto.createCipheriv(
        ALGORITHM,
        sessionKey,
        iv
    );

    // Optional Additional Authenticated Data
    if (aad) {
        cipher.setAAD(Buffer.from(aad, "utf8"));
    }

    const encrypted = Buffer.concat([
        cipher.update(message, "utf8"),
        cipher.final()
    ]);

    // Authentication tag generated by GCM
    const authTag = cipher.getAuthTag(); // always len of 16

    return {
        ciphertext: encrypted,
        key: sessionKey,
        iv,
        authTag
    };
};


export const decryptAESGCM = (
    ciphertext,
    sessionKey,
    iv,
    authTag,
    aad = null
) => {

    try {

         if (!sessionKey) {
            throw new Error("Session key is required");
        }


        const decipher = crypto.createDecipheriv(
            ALGORITHM,
            sessionKey,
            iv
        );

        // Authentication tag MUST be supplied
        decipher.setAuthTag(authTag);

        // Same AAD must be supplied if encryption used it
        if (aad) {
            decipher.setAAD(Buffer.from(aad, "utf8"));
        }

        const decrypted = Buffer.concat([
            decipher.update(ciphertext),
            decipher.final()
        ]);

        return {
            success: true,
            plaintext: decrypted.toString("utf8")
        };

    } catch (error) {

        return {
            success: false,
            plaintext: null,
            error: error.message
        };
    }
};